[project]
name = "ib_async"
requires-python = ">=3.10"
version = "2.1.0"

[tool.poetry]
name = "ib_async"
version = "2.1.0"
description = "Python sync/async framework for Interactive Brokers API"
authors = ["Ewald de Wit"]
maintainers = ["Matt Stancliff <matt@matt.sh>"]
 
readme = "README.md"
include = ["ib_async/py.typed"]


[tool.poetry.dependencies]
python = ">=3.10"
aeventkit = "^2.1.0"
nest_asyncio = "*"
tzdata = "^2025.2"
pandas = "^2.2.1"
